import { eq, and, gte, lte, desc } from 'drizzle-orm';
import { db } from '../index';
import { signals, type Signal, type NewSignal } from '../schema';

/**
 * Signal Repository
 * Manages trading signals generated by the evolution system
 */
export class SignalRepository {
  /**
   * Create a new signal
   */
  async createSignal(data: NewSignal): Promise<Signal> {
    const [signal] = await db.insert(signals).values(data).returning();
    return signal;
  }

  /**
   * Get signal by ID
   */
  async getSignalById(signalId: string): Promise<Signal | null> {
    const [signal] = await db
      .select()
      .from(signals)
      .where(eq(signals.signalId, signalId))
      .limit(1);
    return signal || null;
  }

  /**
   * Get pending signals
   */
  async getPendingSignals(): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(eq(signals.status, 'pending'))
      .orderBy(desc(signals.timestamp));
  }

  /**
   * Update signal status
   */
  async updateSignalStatus(
    signalId: string,
    status: 'pending' | 'approved' | 'rejected' | 'executed'
  ): Promise<Signal | null> {
    const [signal] = await db
      .update(signals)
      .set({ status })
      .where(eq(signals.signalId, signalId))
      .returning();
    return signal || null;
  }

  /**
   * Get signals by evolution generation
   */
  async getSignalsByGeneration(generationNumber: number): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(eq(signals.evolutionGeneration, generationNumber))
      .orderBy(desc(signals.timestamp));
  }

  /**
   * Get signals by symbol
   */
  async getSignalsBySymbol(symbol: string): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(eq(signals.symbol, symbol))
      .orderBy(desc(signals.timestamp));
  }

  /**
   * Get signals by status
   */
  async getSignalsByStatus(status: 'pending' | 'approved' | 'rejected' | 'executed'): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(eq(signals.status, status))
      .orderBy(desc(signals.timestamp));
  }

  /**
   * Get signals by type
   */
  async getSignalsByType(signalType: 'STRONG_BUY' | 'BUY' | 'SELL' | 'STRONG_SELL'): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(eq(signals.signalType, signalType))
      .orderBy(desc(signals.timestamp));
  }

  /**
   * Get recent signals
   */
  async getRecentSignals(limit: number = 50): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .orderBy(desc(signals.timestamp))
      .limit(limit);
  }

  /**
   * Get signals by date range
   */
  async getSignalsByDateRange(startDate: Date, endDate: Date): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(
        and(
          gte(signals.timestamp, startDate),
          lte(signals.timestamp, endDate)
        )
      )
      .orderBy(desc(signals.timestamp));
  }

  /**
   * Get signals by minimum confidence
   */
  async getSignalsByMinConfidence(minConfidence: number): Promise<Signal[]> {
    return db
      .select()
      .from(signals)
      .where(eq(signals.status, 'pending'))
      .orderBy(desc(signals.confidence));
  }

  /**
   * Get signal statistics
   */
  async getSignalStats(): Promise<{
    totalSignals: number;
    pendingSignals: number;
    approvedSignals: number;
    rejectedSignals: number;
    executedSignals: number;
    avgConfidence: number;
  }> {
    const [total] = await db
      .select({ count: sql<number>`count(*)` })
      .from(signals);

    const [pending] = await db
      .select({ count: sql<number>`count(*)` })
      .from(signals)
      .where(eq(signals.status, 'pending'));

    const [approved] = await db
      .select({ count: sql<number>`count(*)` })
      .from(signals)
      .where(eq(signals.status, 'approved'));

    const [rejected] = await db
      .select({ count: sql<number>`count(*)` })
      .from(signals)
      .where(eq(signals.status, 'rejected'));

    const [executed] = await db
      .select({ count: sql<number>`count(*)` })
      .from(signals)
      .where(eq(signals.status, 'executed'));

    const [avgConfidence] = await db
      .select({ avg: sql<number>`avg(confidence)` })
      .from(signals);

    return {
      totalSignals: total.count,
      pendingSignals: pending.count,
      approvedSignals: approved.count,
      rejectedSignals: rejected.count,
      executedSignals: executed.count,
      avgConfidence: avgConfidence.avg || 0,
    };
  }

  /**
   * Delete signal
   */
  async deleteSignal(signalId: string): Promise<boolean> {
    const result = await db.delete(signals).where(eq(signals.signalId, signalId));
    return result.rowCount > 0;
  }
}

/**
 * Singleton instance of SignalRepository
 */
export const signalRepository = new SignalRepository();
