-- Initial schema migration for EURABAY Living System v5.0
-- This migration creates all required tables for the database integration

-- Users table
-- Stores user account information with authentication data
CREATE TABLE IF NOT EXISTS `users` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL UNIQUE,
	`passwordHash` text NOT NULL,
	`name` text NOT NULL,
	`role` text NOT NULL DEFAULT 'viewer', -- admin|trader|viewer
	`emailVerified` integer NOT NULL DEFAULT 0, -- boolean as integer
	`image` text,
	`createdAt` integer NOT NULL, -- timestamp as integer
	`updatedAt` integer NOT NULL -- timestamp as integer
);

-- Sessions table for Better Auth
-- Stores user session data for authentication
CREATE TABLE IF NOT EXISTS `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`token` text NOT NULL,
	`expires_at` integer NOT NULL, -- timestamp as integer
	`ip_address` text,
	`user_agent` text,
	`created_at` integer NOT NULL, -- timestamp as integer
	`updated_at` integer NOT NULL, -- timestamp as integer
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
);

-- Accounts table for Better Auth
-- Stores account information for OAuth providers and email/password auth
CREATE TABLE IF NOT EXISTS `accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`account_id` text NOT NULL,
	`provider_id` text NOT NULL,
	`access_token` text,
	`refresh_token` text,
	`access_token_expires_at` integer, -- timestamp as integer
	`refresh_token_expires_at` integer, -- timestamp as integer
	`scope` text,
	`id_token` text,
	`password` text,
	`created_at` integer NOT NULL, -- timestamp as integer
	`updated_at` integer NOT NULL, -- timestamp as integer
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
);

-- Trades table
-- Stores MT5 trading data with AI evolution tracking
CREATE TABLE IF NOT EXISTS `trades` (
	`system_ticket` text PRIMARY KEY NOT NULL,
	`mt5_ticket` integer NOT NULL UNIQUE,
	`symbol` text NOT NULL,
	`direction` text NOT NULL, -- BUY|SELL
	`lots` real NOT NULL,
	`entry_price` real NOT NULL,
	`current_price` real,
	`stop_loss` real,
	`take_profit` real,
	`open_time` integer NOT NULL, -- timestamp as integer
	`close_time` integer, -- timestamp as integer
	`pnl` real,
	`status` text NOT NULL DEFAULT 'pending', -- active|closed|pending
	`evolution_generation` integer,
	`features_used` text, -- JSON string
	`confidence` real,
	`user_id` text NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`)
);

-- Evolution generations table
-- Tracks evolution cycles and their performance
CREATE TABLE IF NOT EXISTS `evolution_generations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`generation_number` integer NOT NULL UNIQUE,
	`timestamp` integer NOT NULL, -- timestamp as integer
	`fitness` real NOT NULL,
	`avg_performance` real NOT NULL,
	`controller_decision` text NOT NULL,
	`reason` text NOT NULL
);

-- Features table
-- Stores evolved trading features and their performance metrics
CREATE TABLE IF NOT EXISTS `features` (
	`feature_id` text PRIMARY KEY NOT NULL,
	`feature_name` text NOT NULL,
	`success_rate` real NOT NULL,
	`total_uses` integer NOT NULL DEFAULT 0,
	`wins` integer NOT NULL DEFAULT 0,
	`losses` integer NOT NULL DEFAULT 0,
	`avg_pnl` real NOT NULL,
	`created_at` integer NOT NULL, -- timestamp as integer
	`updated_at` integer NOT NULL -- timestamp as integer
);

-- Mutations table
-- Tracks mutation history with evolution and feature relationships
CREATE TABLE IF NOT EXISTS `mutations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`mutation_type` text NOT NULL,
	`generation_id` integer NOT NULL,
	`target_feature_id` text NOT NULL,
	`success` integer NOT NULL, -- boolean as integer
	`fitness_improvement` real NOT NULL,
	`timestamp` integer NOT NULL, -- timestamp as integer
	FOREIGN KEY (`generation_id`) REFERENCES `evolution_generations`(`id`),
	FOREIGN KEY (`target_feature_id`) REFERENCES `features`(`feature_id`)
);

-- System logs table
-- Stores system events and diagnostic information
CREATE TABLE IF NOT EXISTS `system_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`timestamp` integer NOT NULL, -- timestamp as integer
	`level` text NOT NULL, -- INFO|WARN|ERROR|DEBUG
	`component` text NOT NULL,
	`message` text NOT NULL,
	`details` text -- JSON string
);

-- Signals table
-- Stores trading signals generated by the evolution system
CREATE TABLE IF NOT EXISTS `signals` (
	`signal_id` text PRIMARY KEY NOT NULL,
	`symbol` text NOT NULL,
	`signal_type` text NOT NULL, -- STRONG_BUY|BUY|SELL|STRONG_SELL
	`confidence` real NOT NULL,
	`htf_context` text,
	`features_used` text, -- JSON string
	`status` text NOT NULL DEFAULT 'pending', -- pending|approved|rejected|executed
	`timestamp` integer NOT NULL, -- timestamp as integer
	`evolution_generation` integer
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS `idx_trades_user_id` ON `trades` (`user_id`);
CREATE INDEX IF NOT EXISTS `idx_trades_status` ON `trades` (`status`);
CREATE INDEX IF NOT EXISTS `idx_trades_symbol` ON `trades` (`symbol`);
CREATE INDEX IF NOT EXISTS `idx_sessions_user_id` ON `sessions` (`user_id`);
CREATE INDEX IF NOT EXISTS `idx_accounts_user_id` ON `accounts` (`user_id`);
CREATE INDEX IF NOT EXISTS `idx_mutations_generation_id` ON `mutations` (`generation_id`);
CREATE INDEX IF NOT EXISTS `idx_mutations_target_feature_id` ON `mutations` (`target_feature_id`);
CREATE INDEX IF NOT EXISTS `idx_system_logs_level` ON `system_logs` (`level`);
CREATE INDEX IF NOT EXISTS `idx_system_logs_component` ON `system_logs` (`component`);
CREATE INDEX IF NOT EXISTS `idx_system_logs_timestamp` ON `system_logs` (`timestamp`);
CREATE INDEX IF NOT EXISTS `idx_signals_status` ON `signals` (`status`);
CREATE INDEX IF NOT EXISTS `idx_signals_symbol` ON `signals` (`symbol`);
CREATE INDEX IF NOT EXISTS `idx_signals_timestamp` ON `signals` (`timestamp`);
