"""Initial database schema

Revision ID: d59b1d633e07
Revises: 
Create Date: 2026-01-16 23:46:20.575592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59b1d633e07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='Unique configuration key'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='Configuration value (JSON string for complex values)'),
    sa.Column('description', sa.String(length=500), nullable=False, comment='Human-readable description'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Configuration category (e.g., risk, trading, system)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this configuration is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record update timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_config_category', 'configurations', ['category'], unique=False)
    op.create_index(op.f('ix_configurations_category'), 'configurations', ['category'], unique=False)
    op.create_index(op.f('ix_configurations_config_key'), 'configurations', ['config_key'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Trading symbol'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe (e.g., M1, M5, M15, H1, H4, D1)'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Candle timestamp'),
    sa.Column('open_price', sa.Float(), nullable=False, comment='Open price'),
    sa.Column('high_price', sa.Float(), nullable=False, comment='High price'),
    sa.Column('low_price', sa.Float(), nullable=False, comment='Low price'),
    sa.Column('close_price', sa.Float(), nullable=False, comment='Close price'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='Trading volume'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.CheckConstraint('high_price >= close_price', name='check_high_close'),
    sa.CheckConstraint('high_price >= low_price', name='check_high_low'),
    sa.CheckConstraint('high_price >= open_price', name='check_high_open'),
    sa.CheckConstraint('low_price <= close_price', name='check_low_close'),
    sa.CheckConstraint('low_price <= open_price', name='check_low_open'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_symbol_timeframe_timestamp', 'market_data', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_timeframe'), 'market_data', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='Name of the model'),
    sa.Column('model_type', sa.String(length=50), nullable=False, comment='Model type (e.g., XGBoost, RandomForest)'),
    sa.Column('model_version', sa.String(length=50), nullable=False, comment='Model version identifier'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Symbol this model is trained for'),
    sa.Column('training_samples', sa.Integer(), nullable=False, comment='Number of training samples used'),
    sa.Column('features_used', sa.Text(), nullable=False, comment='JSON string of features used'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='Path to saved model file'),
    sa.Column('accuracy', sa.Float(), nullable=False, comment='Model accuracy (0-1)'),
    sa.Column('precision', sa.Float(), nullable=False, comment='Model precision (0-1)'),
    sa.Column('recall', sa.Float(), nullable=False, comment='Model recall (0-1)'),
    sa.Column('f1_score', sa.Float(), nullable=False, comment='Model F1 score (0-1)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this model is currently active'),
    sa.Column('training_time', sa.DateTime(), nullable=False, comment='Training completion timestamp'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record update timestamp'),
    sa.CheckConstraint('accuracy >= 0 AND accuracy <= 1', name='check_accuracy_range'),
    sa.CheckConstraint('f1_score >= 0 AND f1_score <= 1', name='check_f1_range'),
    sa.CheckConstraint('precision >= 0 AND precision <= 1', name='check_precision_range'),
    sa.CheckConstraint('recall >= 0 AND recall <= 1', name='check_recall_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_is_active'), 'models', ['is_active'], unique=False)
    op.create_index(op.f('ix_models_model_name'), 'models', ['model_name'], unique=False)
    op.create_index('ix_models_name_version', 'models', ['model_name', 'model_version'], unique=False)
    op.create_index(op.f('ix_models_symbol'), 'models', ['symbol'], unique=False)
    op.create_index('ix_models_symbol_active', 'models', ['symbol', 'is_active'], unique=False)
    op.create_index(op.f('ix_models_training_time'), 'models', ['training_time'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False, comment='Time period: daily, weekly, monthly, all_time'),
    sa.Column('period_start', sa.DateTime(), nullable=False, comment='Period start timestamp'),
    sa.Column('period_end', sa.DateTime(), nullable=False, comment='Period end timestamp'),
    sa.Column('total_trades', sa.Integer(), nullable=False, comment='Total number of trades'),
    sa.Column('winning_trades', sa.Integer(), nullable=False, comment='Number of winning trades'),
    sa.Column('losing_trades', sa.Integer(), nullable=False, comment='Number of losing trades'),
    sa.Column('win_rate', sa.Float(), nullable=False, comment='Win rate percentage (0-100)'),
    sa.Column('total_profit', sa.Float(), nullable=False, comment='Total profit amount'),
    sa.Column('total_loss', sa.Float(), nullable=False, comment='Total loss amount'),
    sa.Column('profit_factor', sa.Float(), nullable=False, comment='Profit factor ratio (gross profit / gross loss)'),
    sa.Column('average_win', sa.Float(), nullable=False, comment='Average winning trade amount'),
    sa.Column('average_loss', sa.Float(), nullable=False, comment='Average losing trade amount'),
    sa.Column('max_drawdown', sa.Float(), nullable=False, comment='Maximum drawdown amount'),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False, comment='Maximum drawdown percentage'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True, comment='Sharpe ratio'),
    sa.Column('sortino_ratio', sa.Float(), nullable=True, comment='Sortino ratio'),
    sa.Column('calmar_ratio', sa.Float(), nullable=True, comment='Calmar ratio'),
    sa.Column('equity_curve', sa.JSON(), nullable=True, comment='Equity curve data points'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record update timestamp'),
    sa.CheckConstraint("period IN ('daily', 'weekly', 'monthly', 'all_time')", name='check_period_type'),
    sa.CheckConstraint('win_rate >= 0 AND win_rate <= 100', name='check_win_rate_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_period'), 'performance_metrics', ['period'], unique=False)
    op.create_index(op.f('ix_performance_metrics_period_end'), 'performance_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_performance_metrics_period_start'), 'performance_metrics', ['period_start'], unique=False)
    op.create_index('ix_performance_period', 'performance_metrics', ['period', 'period_start', 'period_end'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mt5_ticket', sa.Integer(), nullable=True, comment='MT5 ticket number for the trade'),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Trading symbol (e.g., V10, V25, V50, V75, V100)'),
    sa.Column('direction', sa.String(length=4), nullable=False, comment='Trade direction: BUY or SELL'),
    sa.Column('entry_price', sa.Float(), nullable=False, comment='Entry price'),
    sa.Column('entry_time', sa.DateTime(), nullable=False, comment='Entry timestamp'),
    sa.Column('exit_price', sa.Float(), nullable=True, comment='Exit price'),
    sa.Column('exit_time', sa.DateTime(), nullable=True, comment='Exit timestamp'),
    sa.Column('stop_loss', sa.Float(), nullable=True, comment='Stop loss price'),
    sa.Column('take_profit', sa.Float(), nullable=True, comment='Take profit price'),
    sa.Column('lot_size', sa.Float(), nullable=False, comment='Position size in lots'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Signal confidence (0-1)'),
    sa.Column('strategy_used', sa.String(length=100), nullable=False, comment='Strategy name that generated the signal'),
    sa.Column('profit_loss', sa.Float(), nullable=True, comment='Profit/loss in account currency'),
    sa.Column('profit_loss_pips', sa.Float(), nullable=True, comment='Profit/loss in pips'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='Trade status: OPEN, CLOSED, PENDING'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Record update timestamp'),
    sa.CheckConstraint("direction IN ('BUY', 'SELL')", name='check_trade_direction'),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED', 'PENDING')", name='check_trade_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='check_confidence_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_entry_time', 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trades_exit_time'), 'trades', ['exit_time'], unique=False)
    op.create_index(op.f('ix_trades_mt5_ticket'), 'trades', ['mt5_ticket'], unique=True)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_status', 'trades', ['symbol', 'status'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False, comment='Trading symbol'),
    sa.Column('direction', sa.String(length=10), nullable=False, comment='Signal direction: BUY, SELL, WAIT'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Signal confidence (0-1)'),
    sa.Column('price', sa.Float(), nullable=False, comment='Price at signal generation'),
    sa.Column('strategy', sa.String(length=100), nullable=False, comment='Strategy that generated the signal'),
    sa.Column('reasons', sa.JSON(), nullable=True, comment='List of reasons for the signal'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Signal generation timestamp'),
    sa.Column('executed', sa.Boolean(), nullable=False, comment='Whether signal was executed'),
    sa.Column('trade_id', sa.Integer(), nullable=True, comment='Associated trade ID if executed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Record creation timestamp'),
    sa.CheckConstraint("direction IN ('BUY', 'SELL', 'WAIT')", name='check_signal_direction'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='check_signal_confidence'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_direction'), 'signals', ['direction'], unique=False)
    op.create_index('ix_signals_executed', 'signals', ['executed'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_timestamp', 'signals', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_signals_timestamp'), 'signals', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_timestamp'), table_name='signals')
    op.drop_index('ix_signals_symbol_timestamp', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index('ix_signals_executed', table_name='signals')
    op.drop_index(op.f('ix_signals_direction'), table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_trades_symbol_status', table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_mt5_ticket'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_time'), table_name='trades')
    op.drop_index('ix_trades_entry_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_performance_period', table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_period_start'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_period_end'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_period'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_models_training_time'), table_name='models')
    op.drop_index('ix_models_symbol_active', table_name='models')
    op.drop_index(op.f('ix_models_symbol'), table_name='models')
    op.drop_index('ix_models_name_version', table_name='models')
    op.drop_index(op.f('ix_models_model_name'), table_name='models')
    op.drop_index(op.f('ix_models_is_active'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_timeframe'), table_name='market_data')
    op.drop_index('ix_market_data_symbol_timeframe_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_configurations_config_key'), table_name='configurations')
    op.drop_index(op.f('ix_configurations_category'), table_name='configurations')
    op.drop_index('ix_config_category', table_name='configurations')
    op.drop_table('configurations')
    # ### end Alembic commands ###
